background {
    monitor =
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 0
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.3
    fade_on_empty = true
    placeholder_text = <i>Contraseña...</i>
    hide_input = false
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 90
    position = 0, 100
    halign = center
    valign = center
}
